# Generated by Django 4.1.2 on 2023-04-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "objId",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("objState", models.CharField(max_length=6)),
                ("objDistrict", models.CharField(max_length=30)),
                ("objAddress", models.CharField(max_length=120)),
                ("objType", models.IntegerField()),
                ("objStatus", models.IntegerField()),
                ("objArea", models.IntegerField()),
                ("objOwner", models.CharField(max_length=50)),
                ("objUser", models.CharField(max_length=50)),
                (
                    "objImage",
                    models.ImageField(
                        default="/default_logo/favicon.ico", upload_to="images/"
                    ),
                ),
            ],
        ),
    ]
