# Generated by Django 4.1.2 on 2023-04-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="objState",
            field=models.CharField(max_length=5),
        ),
    ]
