# Generated by Django 4.1.2 on 2023-04-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_building_objstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="objState",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="building",
            name="objStatus",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="building",
            name="objType",
            field=models.CharField(max_length=16),
        ),
    ]
