# Generated by Django 4.1.2 on 2023-04-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_building_objstate_alter_building_objstatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="objImage",
            field=models.ImageField(default="images/7fIzRQy.png", upload_to="images/"),
        ),
    ]
