# Generated by Django 4.1.7 on 2023-04-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_building_objstatus_alter_building_objtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='objImage',
            field=models.ImageField(default='default/default.png', upload_to='images/'),
        ),
    ]
