# Generated by Django 4.1.2 on 2023-04-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_workgroup_buildingsids_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workgroup",
            old_name="buildingsIds",
            new_name="buildings",
        ),
        migrations.RenameField(
            model_name="workgroup",
            old_name="usernames",
            new_name="users",
        ),
    ]
