# Generated by Django 4.1.2 on 2023-04-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_building_objimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workgroup",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
